[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hero_game = "7Yzbjo3ptcfbK1M4oTHxaGZPkZN1WYgVVjXkqAW94VF3"

[programs.devnet]
hero_game = "7Yzbjo3ptcfbK1M4oTHxaGZPkZN1WYgVVjXkqAW94VF3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
